name: Validate with hassfest

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3.2.0
      - name: 🏃 Hassfest validation
        uses: home-assistant/actions/hassfest@master
        with:
          category: netdaemon
